# Generated by Django 2.2 on 2022-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20221128_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_roles',
        ),
        migrations.AddField(
            model_name='candidate',
            name='access_level',
            field=models.CharField(choices=[('Engineer(core,non-IT)', 'Engineer(core,non-IT)'), ('IT-Hardware Engineer', 'IT-Hardware Engineer'), ('IT Software-Engineer', 'IT Software-Engineer')], db_index=True, default='Engineer(core,non-IT)', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(default='admin', max_length=20, unique=True),
        ),
    ]
