# Generated by Django 2.2 on 2022-11-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20221128_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='access_level',
            new_name='role',
        ),
    ]
