# Generated by Django 2.2 on 2022-12-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20221216_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentactivitybktest',
            name='dialer_idle_time',
        ),
        migrations.RemoveField(
            model_name='agentactivitybktest',
            name='pause_progressive_time',
        ),
        migrations.RemoveField(
            model_name='agentactivitybktest',
            name='preview_time',
        ),
        migrations.RemoveField(
            model_name='agentactivitybktest',
            name='progressive_time',
        ),
    ]
